#  The following code example is described in the book "Introduction
#  to Geometric Computing" by Sherif Ghali, Springer-Verlag, 2008.
#  
#  Copyright (C) 2008 Sherif Ghali. This code may be freely copied,
#  modified, or republished electronically or in print provided that
#  this copyright notice appears in all copies. This software is
#  provided "as is" without express or implied warranty; not even for
#  merchantability or fitness for a particular purpose.

GDIRS = \
	01-glVertex                \
	02-misc/02-01-force-error  \
	02-misc/02-02-display-list \
	03-matrices                \
	04-lighting                

include ../../Makefile-subdirs.mk
