#  The following code example is described in the book "Introduction
#  to Geometric Computing" by Sherif Ghali, Springer-Verlag, 2008.
#  
#  Copyright (C) 2008 Sherif Ghali. This code may be freely copied,
#  modified, or republished electronically or in print provided that
#  this copyright notice appears in all copies. This software is
#  provided "as is" without express or implied warranty; not even for
#  merchantability or fitness for a particular purpose.

GDIRS = \
	01-create-window        \
	02-keyboard-event       \
	03-idle-events          \
	04-onreshape            \
	05-simple-widgets       \
	06-arcball-manipulation \
	07-frame-rate	   	\
	08-frame-rate-in-widget \
	09-widgets-in-gl-window 

include ../../Makefile-subdirs.mk
