#  The following code example is described in the book "Introduction
#  to Geometric Computing" by Sherif Ghali, Springer-Verlag, 2008.
#  
#  Copyright (C) 2008 Sherif Ghali. This code may be freely copied,
#  modified, or republished electronically or in print provided that
#  this copyright notice appears in all copies. This software is
#  provided "as is" without express or implied warranty; not even for
#  merchantability or fitness for a particular purpose.

GDIRS = \
	01-intersecting-medians \
	02-colinear-points \
	03-cocircular-points \
	04-float-to-binary \
	05-binary-to-float \
	06-coincidence-gl \
	07-coincidence-ps \
	08-orientation-robustness \
	precision

include ../../Makefile-subdirs.mk

